### ISSUE TITLE
clearml-serving not working with newer numpy 1.24

### ISSUE THREAD

**Issue by cajewsa** [allegroai/clearml-serving#41]
I am unable to use `clearml-serving` for model deployment on my setup.

OS: Ubuntu 22.04 Server LTS
Python: 3.10.6

Steps:
1. `pip install clearml-serving`
2. `clearml-serving create --name "serving example"`

I get the following error:
```
Traceback (most recent call last):
  File "/home/user_65s/.local/bin/clearml-serving", line 5, in <module>
    from clearml_serving.__main__ import main
  File "/home/user_65s/.local/lib/python3.10/site-packages/clearml_serving/__main__.py", line 9, in <module>
    from clearml_serving.serving.model_request_processor import ModelRequestProcessor, CanaryEP
  File "/home/user_65s/.local/lib/python3.10/site-packages/clearml_serving/serving/model_request_processor.py", line 18, in <module>
    from .preprocess_service import BasePreprocessRequest
  File "/home/user_65s/.local/lib/python3.10/site-packages/clearml_serving/serving/preprocess_service.py", line 247, in <module>
    class TritonPreprocessRequest(BasePreprocessRequest):
  File "/home/user_65s/.local/lib/python3.10/site-packages/clearml_serving/serving/preprocess_service.py", line 253, in TritonPreprocessRequest
    np.int: 'int_contents',
  File "/home/user_65s/.local/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?
```

It appears you are using `np.int` internally which has been deprecated since numpy 1.20:
> 1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

When I downgrade to `numpy==1.23.*` it works.

**Comment by thepycoder** [comment]
Thanks for taking the time to log the issue! I've submitted a PR :)

**Comment by amirhmk** [comment]
Hi, i'm still facing this issue in `clearml-serving==1.2.0` and `numpy==1.24.2`. Was this not fixed, or just not released yet?

**Comment by ainoam** [comment]
@amirhmk You'll note the PR was merged after v1.2.0 was already out, so simply not released yet.

**Comment by besrym** [comment]
@amirhmk +1 

downgrading numpy to 1.23.* helps temporarily until the release is out. 

`pip install numpy=1.23.*` --> see @cajewsa
